apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "6441699cbf1a52d68ba296a82a218f70"
spec:
  displayName: "pl_dmp_oneapp_scroring_layer"
  description: "150083be-0000-4200-0000-6a28c9960000"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "oneapp_dmp_scroring_layer"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/User/demo/etl_pipeline/pl_dmp_oneapp_scroring_layer/activities/oneapp_dmp_scroring_layer/oneapp_dmp_scroring_layer.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
  - name: "Copy_to_DMP_DB"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/User/demo/etl_pipeline/pl_dmp_oneapp_scroring_layer/activities/Copy_to_DMP_DB/Copy_to_DMP_DB.json"
    dependsOn:
      activities:
      - name: "create_temp_table"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 2
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "create_temp_table"
    type: "look_up"
    dataSource: "ls_asql_offdmp_2"
    table: "ds_asql_db202_dbo_with_out_parameter"
    dependsOn:
      activities:
      - name: "oneapp_dmp_scroring_layer"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "create_index_fro_temp_table"
    type: "look_up"
    dataSource: "ls_asql_offdmp_2"
    table: "ds_asql_db202_dbo_with_out_parameter"
    dependsOn:
      activities:
      - name: "Copy_to_DMP_DB"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "drop_and_sp_rename_temp_table"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/User/demo/etl_pipeline/pl_dmp_oneapp_scroring_layer/activities/drop_and_sp_rename_temp_table/drop_and_sp_rename_temp_table.json"
    dependsOn:
      activities:
      - name: "create_index_fro_temp_table"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 2
      minRetryIntervalMillis: 60000
      timeoutSeconds: 604800
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
