apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "949b7b7cfd31f2323df23bbce00508c6"
spec:
  displayName: "pl_dbrs_fix_ingst_app01_psql_main"
  runAs: "Account/2100052957"
  trigger:
    type: "SCHEDULED"
    pauseStatus: "UNPAUSED"
    frequency: "daily"
    cronExpression: "0 0 3 * * ?"
    priority: "d5"
  activities:
  - name: "GetJobList"
    type: "look_up"
    dataSource: "pl_dbrs_fix_ingst_salesforce_psql_main_support_live_sanitized__ls_asql_infra_03"
    table: "<<REDACTED>>"
    dependsOn:
      activities:
      - name: "SetEndDate"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "GetPartitionID"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "partition_id"
    value:
      rawValue: "@if(equals(pipeline().parameters.PartitionID,'0'),formatDateTime(adddays(addhours(utcnow(),8),-1),'yyyy-MM-dd'),pipeline().parameters.PartitionID)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "IterateEachJob"
    type: "for_each"
    items: "@activity('GetJobList').output.value"
    concurrency: 3
    activities:
    - name: "pl_dbrs_fix_ingst_app01_psql_detail1"
      type: "execute_pipeline"
      pipelineName: "pl_dbrs_fix_ingst_app01_psql_detail1"
      pipelineId: "1b4a5cf96d9fe1a7032ffedaa8c78152"
      projectId: "10926"
      bizDate: "${DATE}"
      pipelineParameterValues:
        LogEnabled: ""
        partition_id: ""
        DatabaseName: ""
        TableName: ""
        MainPipelineTriggerType: ""
        is_header: ""
        storage_account: ""
        DataSourceSQL_select: ""
        DataSourceSQL_from: ""
        DataSourceSQL_where: ""
        end_date: ""
        src_level_name: ""
      waitingSuccess: true
    dependsOn:
      activities:
      - name: "GetJobList"
        dependencyConditions:
        - "succeeded"
  - name: "Env"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "Env"
    value:
      rawValue: "@pipeline().globalParameters.Environment"
    outputVariables: []
  - name: "If_Condition1"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "{{pipeline.vars.Env}}"
      op: "EQUAL_TO"
      right: "INT"
    dependsOn:
      activities:
      - name: "Env"
        dependencyConditions:
        - "succeeded"
  - name: "storage_account_INT"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "storage_account"
    value:
      rawValue: "<<REDACTED>>"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "storage_account_prod"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "storage_account"
    value:
      rawValue: "<<REDACTED>>"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "SetEndDate"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "end_date"
    value:
      rawValue: "@formatDateTime(adddays(variables('partition_id'),1),'yyyy-MM-dd')\n"
    outputVariables: []
    dependsOn:
      activities:
      - name: "GetPartitionID"
        dependencyConditions:
        - "succeeded"
  - name: "pl_dbrs_fix_ingst_app01_psql_detail2"
    type: "execute_pipeline"
    pipelineName: "pl_dbrs_fix_ingst_app01_psql_detail2"
    pipelineId: "33c740891dce156b8137c7fb4d4ad64c"
    projectId: "10926"
    bizDate: "${DATE}"
    pipelineParameterValues:
      LogEnabled: ""
      MainPipelineTriggerType: ""
      partition_id: ""
      TableName: "dw_dealer_sfdc_vhcldl"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "IterateEachJob"
        dependencyConditions:
        - "completed"
  - name: "CCDD_DW"
    type: "execute_pipeline"
    pipelineName: "pl_dbrs_fix_ingst_salesforce_psql_main_support_live_sanitized__pl_dbrs_fix_ccdd_deletion"
    pipelineId: "a94540cbba0c7bacecfb7590993d1ae3"
    projectId: "10926"
    bizDate: "${DATE}"
    pipelineParameterValues:
      app_name: "crm_dw"
      start_time_api: "NA"
      end_time_api: "NA"
      del_table_name: "NA"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "IterateEachJob"
        dependencyConditions:
        - "completed"
  - name: "CCDD_RW"
    type: "execute_pipeline"
    pipelineName: "pl_dbrs_fix_ingst_salesforce_psql_main_support_live_sanitized__pl_dbrs_fix_ccdd_deletion"
    pipelineId: "a94540cbba0c7bacecfb7590993d1ae3"
    projectId: "10926"
    bizDate: "${DATE}"
    pipelineParameterValues:
      app_name: "crm_rw"
      start_time_api: "NA"
      end_time_api: "NA"
      del_table_name: "NA"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "CCDD_DW"
        dependencyConditions:
        - "succeeded"
  parameters:
  - name: "LogEnabled"
    default: "1"
  - name: "TableName"
    default: "ALL"
  - name: "PartitionID"
    default: "0"
  - name: "is_header"
    default: "False"
  variables:
  - name: "partition_id"
    default: ""
  - name: "JobNameVar"
    default: ""
  - name: "Env"
    default: ""
  - name: "storage_account"
    default: ""
  - name: "end_date"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
