apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "30f9b65a9d6a119955050908552a24f5"
spec:
  displayName: "pl_dbrs_fix_ingst_sop_http_main_support_live_sanitized__pl_dbrs_fix_ingst_app01_http_detail"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "StartLogRecord"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_sop_http_main_support_live_sanitized__pl_dbrs_fix_ingst_app01_http_detail/activities/StartLogRecord/StartLogRecord.json"
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 300000
      timeoutSeconds: 604800
  - name: "If_Condition1"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "@Or(Equals(pipeline().TriggerType,'Manual'),Equals(pipeline().parameters.MainPipelineTriggerType,\
        \ 'Manual'))"
      op: "EQUAL_TO"
      right: "true"
  - name: "Manual"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@concat('$M$_',replace(pipeline().parameters.TableName,'rw_','dw_'))"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "Auto"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@replace(pipeline().parameters.TableName,'rw_','dw_')"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "src_to_dl"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_sop_http_main_support_live_sanitized__pl_dbrs_fix_ingst_app01_http_detail/activities/src_to_dl/src_to_dl.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "StartLogRecord"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 300000
      timeoutSeconds: 10800
  - name: "Sop2Hive_fail"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_sop_http_main_support_live_sanitized__pl_dbrs_fix_ingst_app01_http_detail/activities/Sop2Hive_fail/Sop2Hive_fail.json"
    dependsOn:
      activities:
      - name: "src_to_dl"
        dependencyConditions:
        - "failed"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "LogCount"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_sop_http_main_support_live_sanitized__pl_dbrs_fix_ingst_app01_http_detail/activities/LogCount/LogCount.json"
    dependsOn:
      activities:
      - name: "src_to_dl"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 300000
      timeoutSeconds: 604800
  parameters:
  - name: "LogEnabled"
    default: ""
  - name: "partition_id"
    default: ""
  - name: "TableName"
    default: ""
  - name: "MainPipelineTriggerType"
    default: ""
  - name: "Env"
    default: ""
  variables:
  - name: "JobNameVar"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
