apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "pl_dmp_oneapp_store_recommender_v2_mmc_parallel"
spec:
  displayName: "pl_dmp_oneapp_store_recommender_v2_mmc_parallel"
  description: "04001eb5-0000-4200-0000-69f18c970000"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
    frequency: "daily"
  activities:
  - name: "Extraction"
    type: "execute_pipeline"
    description: "Source: platform=adf, activity type=ExecutePipeline"
    pipelineName: "pl_dmp_oneapp_store_recommender_v2_mmc_data_update"
    pipelineId: "pl_dmp_oneapp_store_recommender_v2_mmc_data_update"
    projectId: "101875"
    bizDate: "${DATE}"
    pipelineParameterValues:
      run_date: "{{pipeline.vars.run_date}}"
      table_config_path: "{{pipeline.params.table_config_path}}"
      model_config_path: "{{pipeline.params.model_config_path}}"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "Set_run_date"
        dependencyConditions:
        - "succeeded"
  - name: "Training"
    type: "execute_pipeline"
    description: "Source: platform=adf, activity type=ExecutePipeline"
    pipelineName: "pl_dmp_oneapp_store_recommender_v2_mmc_training"
    pipelineId: "pl_dmp_oneapp_store_recommender_v2_mmc_training"
    projectId: "101875"
    bizDate: "${DATE}"
    pipelineParameterValues:
      run_date: "{{pipeline.vars.run_date}}"
      table_config_path: "{{pipeline.params.table_config_path}}"
      model_config_path: "{{pipeline.params.model_config_path}}"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "Extraction"
        dependencyConditions:
        - "succeeded"
  - name: "Inference"
    type: "execute_pipeline"
    description: "Source: platform=adf, activity type=ExecutePipeline"
    pipelineName: "pl_dmp_oneapp_store_recommender_v2_mmc_inference_parallel"
    pipelineId: "pl_dmp_oneapp_store_recommender_v2_mmc_inference_parallel"
    projectId: "101875"
    bizDate: "${DATE}"
    pipelineParameterValues:
      run_date: "{{pipeline.vars.run_date}}"
      table_config_path: "{{pipeline.params.table_config_path}}"
      model_config_path: "{{pipeline.params.model_config_path}}"
      parallel_shard_count: "{{pipeline.params.parallel_shard_count}}"
      parallel_batch_count: "{{pipeline.params.parallel_batch_count}}"
      parallel_shard_id_base: "{{pipeline.params.parallel_shard_id_base}}"
      parallel_shard_ids: "{{pipeline.params.parallel_shard_ids}}"
      infer_config_path: "{{pipeline.params.infer_config_path}}"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "Training"
        dependencyConditions:
        - "succeeded"
  - name: "Set_run_date"
    type: "set_variable"
    description: "Set a pipeline variable\nSource: platform=adf, activity type=SetVariable"
    variableType: "PIPELINE_INNER"
    variableName: "run_date"
    value:
      rawValue: "${DATE-1}"
    outputVariables: []
  - name: "pl_dmp_oneapp_scroring_layer_v2"
    type: "execute_pipeline"
    description: "Source: platform=adf, activity type=ExecutePipeline"
    pipelineName: "pl_dmp_oneapp_scroring_layer_v2"
    pipelineId: "pl_dmp_oneapp_scroring_layer_v2"
    projectId: "101875"
    bizDate: "${DATE}"
    pipelineParameterValues:
      dt: "{{pipeline.vars.run_date}}"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "combine_mmc_lpo_prediction_v2"
        dependencyConditions:
        - "succeeded"
  - name: "combine_mmc_lpo_prediction_v2"
    type: "notebook"
    description: "A new Notebook job\nSource: platform=adf, activity type=DatabricksNotebook"
    source: "WORKSPACE"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_store_recommender_v2_mmc_parallel/activities/combine_mmc_lpo_prediction_v2/combine_mmc_lpo_prediction_v2.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1010
    sparkConf:
    - key: "serverless.spark.access.key"
      value: "{{ak}}"
    - key: "serverless.spark.secret.key"
      value: "{{sk}}"
    executeParam:
      image:
        imageUrl: "dataleap-cn-beijing.cr.volces.com/studio/notebook_runtime:python-3-12"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    dependsOn:
      activities:
      - name: "Inference"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 0
      maxRetries: 100
      minRetryIntervalSeconds: 0
  parameters:
  - name: "parallel_shard_count"
    default: "4"
  - name: "parallel_shard_ids"
    default: "0,1,2,3"
  - name: "parallel_batch_count"
    default: "5"
  - name: "table_config_path"
    default: "/Volumes/conf/dmpoff/vol_offdmp_adf_mnt_common_adls2/store_recommender_v2/mmc/config/table_config.json"
  - name: "infer_config_path"
    default: "/Volumes/conf/dmpoff/vol_offdmp_adf_mnt_common_adls2/store_recommender_v2/mmc/config/infer_config.json"
  - name: "model_config_path"
    default: "/Volumes/conf/dmpoff/vol_offdmp_adf_mnt_common_adls2/store_recommender_v2/mmc/config/model_config.json"
  - name: "parallel_shard_id_base"
    default: "0"
  variables:
  - name: "run_date"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1008
  dependsOn:
    pipelines: []
    self:
      enabled: false
