apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "pl_dmp_oneapp_community_recommender"
spec:
  displayName: "pl_dmp_oneapp_community_recommender"
  description: "7b037d10-0000-4200-0000-69c30d330000"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
    frequency: "daily"
  activities:
  - name: "Extraction"
    type: "execute_pipeline"
    description: "Source: platform=adf, activity type=ExecutePipeline"
    pipelineName: "pl_dmp_oneapp_community_recommender_data_update"
    pipelineId: "pl_dmp_oneapp_community_recommender_data_update"
    projectId: "101875"
    bizDate: "${DATE}"
    pipelineParameterValues:
      run_date: "{{pipeline.vars.run_date}}"
      data_config_path: "{{pipeline.params.data_config_path}}"
      two_tower_retriever_config_path: "{{pipeline.params.two_tower_retriever_config_path}}"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "Set_run_date"
        dependencyConditions:
        - "succeeded"
  - name: "Retrieval"
    type: "execute_pipeline"
    description: "Source: platform=adf, activity type=ExecutePipeline"
    pipelineName: "pl_dmp_oneapp_community_recommender_retrieval"
    pipelineId: "pl_dmp_oneapp_community_recommender_retrieval"
    projectId: "101875"
    bizDate: "${DATE}"
    pipelineParameterValues:
      run_date: "{{pipeline.vars.run_date}}"
      data_config_path: "{{pipeline.params.data_config_path}}"
      geo_retriever_config_path: "{{pipeline.params.geo_retriever_config_path}}"
      follower_retriever_config_path: "{{pipeline.params.follower_retriever_config_path}}"
      i2i_retriever_config_path: "{{pipeline.params.i2i_retriever_config_path}}"
      two_tower_retriever_config_path: "{{pipeline.params.two_tower_retriever_config_path}}"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "Extraction"
        dependencyConditions:
        - "succeeded"
  - name: "Ranking"
    type: "execute_pipeline"
    description: "Source: platform=adf, activity type=ExecutePipeline"
    pipelineName: "pl_dmp_oneapp_community_recommender_ranking"
    pipelineId: "pl_dmp_oneapp_community_recommender_ranking"
    projectId: "101875"
    bizDate: "${DATE}"
    pipelineParameterValues:
      run_date: "{{pipeline.vars.run_date}}"
      data_config_path: "{{pipeline.params.data_config_path}}"
      ranker_config_path: "{{pipeline.params.ranker_config_path}}"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "Retrieval"
        dependencyConditions:
        - "succeeded"
  - name: "Set_run_date"
    type: "set_variable"
    description: "Set a pipeline variable\nSource: platform=adf, activity type=SetVariable"
    variableType: "PIPELINE_INNER"
    variableName: "run_date"
    value:
      rawValue: "${DATE}"
    outputVariables: []
  - name: "Content_to_SQS"
    type: "execute_pipeline"
    description: "Source: platform=adf, activity type=ExecutePipeline"
    pipelineName: "pl_dmp_oneapp_community_content_sqs"
    pipelineId: "pl_dmp_oneapp_community_content_sqs"
    projectId: "101875"
    bizDate: "${DATE}"
    pipelineParameterValues:
      Profile: "PROD"
      Mode: "SEND"
      run_date: "{{pipeline.vars.run_date}}"
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "Ranking"
        dependencyConditions:
        - "succeeded"
  parameters:
  - name: "geo_retriever_config_path"
    default: ""
  - name: "data_config_path"
    default: ""
  - name: "i2i_retriever_config_path"
    default: ""
  - name: "follower_retriever_config_path"
    default: ""
  - name: "ranker_config_path"
    default: ""
  - name: "two_tower_retriever_config_path"
    default: ""
  variables:
  - name: "run_date"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1008
  dependsOn:
    pipelines: []
    self:
      enabled: false
