apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "939cd825a26c095d1d0db93900fa326c"
spec:
  displayName: "pl_dbrs_job_ingst_psql_app012srv_prod_main"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "GetJobList"
    type: "look_up"
    dataSource: "pl_dbrs_job_ingst_tire_main2_support_live_sanitized__ls_asql_infra_04"
    table: "pl_dbrs_job_ingst_tire_main2_support_live_sanitized__ds_asql_conf_environment"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "source2raw"
    type: "for_each"
    items: "@activity('GetJobList').output.value"
    concurrency: 5
    activities:
    - name: "pl_dbrs_job_ingst_psql_app012srv_prod_detail"
      type: "execute_pipeline"
      pipelineName: "pl_dbrs_job_ingst_psql_app012srv_prod_detail"
      pipelineId: "c3d9d62bc95b64fbe6456970b7b061e3"
      projectId: "10926"
      bizDate: "${DATE}"
      pipelineParameterValues:
        TableName: ""
        PartitionID: ""
        DatabaseName: ""
        LogEnabled: ""
        MainPipelineTriggerType: ""
        env_storage: ""
        source_select: ""
        source_count: ""
        source_level_name: ""
        pl_name: ""
      waitingSuccess: true
    dependsOn:
      activities:
      - name: "GetJobList"
        dependencyConditions:
        - "succeeded"
  parameters:
  - name: "LogEnabled"
    default: "1"
  - name: "pt"
    default: ""
  - name: "pTableList"
    default: ""
  - name: "pl_name"
    default: ""
  - name: "env_storage"
    default: ""
  - name: "PartitionID"
    default: ""
  - name: "MainPipelineTriggerType"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
