apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "1bc738649045603622a6b3ab8447d106"
spec:
  displayName: "pl_dmp_oneapp_scroring_layer_v2"
  description: "15001ce3-0000-4200-0000-69ef2e4c0000"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "oneapp_dmp_scroring_layer"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dmp_oneapp_scroring_layer_v2/activities/oneapp_dmp_scroring_layer/oneapp_dmp_scroring_layer.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "公共计算"
    computingResourceGroupId: 1012
    sparkConf:
    - key: "serverless.spark.access.key"
      value: "{{ak}}"
    - key: "serverless.spark.secret.key"
      value: "{{sk}}"
    executeParam:
      image:
        imageUrl: "image-repo-cn-beijing.cr.volces.com/emr-serverless-spark/spark:3.5.1-py3.12-ubuntu20.04-802"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 0
      maxRetries: 100
      minRetryIntervalSeconds: 0
  - name: "Copy_to_DMP_DB"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/libopeng_folder/pl_dmp_oneapp_scroring_layer_v2/activities/Copy_to_DMP_DB/Copy_to_DMP_DB.json"
    dependsOn:
      activities:
      - name: "create_temp_table"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      timeoutSeconds: 43200
      maxRetries: 2
      minRetryIntervalSeconds: 30
  - name: "create_temp_table"
    type: "look_up"
    dataSource: "ls_asql_offdmp_2"
    table: "ds_asql_db202_dbo_with_out_parameter"
    dependsOn:
      activities:
      - name: "oneapp_dmp_scroring_layer"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      timeoutSeconds: 43200
      maxRetries: 0
      minRetryIntervalSeconds: 30
  - name: "create_index_fro_temp_table"
    type: "look_up"
    dataSource: "ls_asql_offdmp_2"
    table: "ds_asql_db202_dbo_with_out_parameter"
    dependsOn:
      activities:
      - name: "Copy_to_DMP_DB"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      timeoutSeconds: 43200
      maxRetries: 0
      minRetryIntervalSeconds: 30
  - name: "drop_and_sp_rename_temp_table"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dmp_oneapp_scroring_layer_v2/activities/drop_and_sp_rename_temp_table/drop_and_sp_rename_temp_table.json"
    dependsOn:
      activities:
      - name: "create_index_fro_temp_table"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      timeoutSeconds: 604800
      maxRetries: 2
      minRetryIntervalSeconds: 60
  schedulingResourceGroupName: "公共调度资源组"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
