apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "pl_dmp_oneapp_scroring_layer_v2"
spec:
  displayName: "pl_dmp_oneapp_scroring_layer_v2"
  description: "15001ce3-0000-4200-0000-69ef2e4c0000"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
    frequency: "daily"
  activities:
  - name: "oneapp_dmp_scroring_layer"
    type: "notebook"
    description: "A new Notebook job\nSource: platform=adf, activity type=DatabricksNotebook"
    source: "WORKSPACE"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_scroring_layer_v2/activities/oneapp_dmp_scroring_layer/oneapp_dmp_scroring_layer.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1010
    sparkConf:
    - key: "serverless.spark.access.key"
      value: "{{ak}}"
    - key: "serverless.spark.secret.key"
      value: "{{sk}}"
    executeParam:
      image:
        imageUrl: "dataleap-cn-beijing.cr.volces.com/studio/notebook_runtime:python-3-12"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 0
      maxRetries: 100
      minRetryIntervalSeconds: 0
  - name: "Copy_to_DMP_DB"
    type: "dts_batch"
    description: "A new Copy Data job\nSource: platform=adf, activity type=Copy"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_scroring_layer_v2/activities/Copy_to_DMP_DB/Copy_to_DMP_DB.json"
    dependsOn:
      activities:
      - name: "create_temp_table"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      timeoutSeconds: 43200
      maxRetries: 2
      minRetryIntervalSeconds: 30
  - name: "create_temp_table"
    type: "notebook"
    description: "A new Notebook job\nSource: platform=adf, activity type=Lookup"
    source: "WORKSPACE"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_scroring_layer_v2/activities/create_temp_table/create_temp_table.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1010
    sparkConf: []
    executeParam:
      image:
        imageUrl: "dataleap-cn-beijing.cr.volces.com/studio/notebook_runtime:python-3-12"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    dependsOn:
      activities:
      - name: "oneapp_dmp_scroring_layer"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 43200
      maxRetries: 0
      minRetryIntervalSeconds: 30
  - name: "create_index_fro_temp_table"
    type: "notebook"
    description: "A new Notebook job\nSource: platform=adf, activity type=Lookup"
    source: "WORKSPACE"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_scroring_layer_v2/activities/create_index_fro_temp_table/create_index_fro_temp_table.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1010
    sparkConf: []
    executeParam:
      image:
        imageUrl: "dataleap-cn-beijing.cr.volces.com/studio/notebook_runtime:python-3-12"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    dependsOn:
      activities:
      - name: "Copy_to_DMP_DB"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 43200
      maxRetries: 0
      minRetryIntervalSeconds: 30
  - name: "drop_and_sp_rename_temp_table"
    type: "notebook"
    description: "A new Notebook job\nSource: platform=adf, activity type=SqlServerStoredProcedure"
    source: "WORKSPACE"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_scroring_layer_v2/activities/drop_and_sp_rename_temp_table/drop_and_sp_rename_temp_table.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1010
    sparkConf: []
    executeParam:
      image:
        imageUrl: "dataleap-cn-beijing.cr.volces.com/studio/notebook_runtime:python-3-12"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    dependsOn:
      activities:
      - name: "create_index_fro_temp_table"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 604800
      maxRetries: 2
      minRetryIntervalSeconds: 60
  parameters:
  - name: "dt"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1008
  dependsOn:
    pipelines: []
    self:
      enabled: false
