apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "5b39ff508b8a575aa1ca800b9f23eac7"
spec:
  displayName: "pl_dbrs_fix_export_app01_2_rd_main"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "Start_SqlServerStoredProcedure"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_export_app01_2_rd_main/activities/Start_SqlServerStoredProcedure/Start_SqlServerStoredProcedure.json"
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "BLM2Blob_success"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_export_app01_2_rd_main/activities/BLM2Blob_success/BLM2Blob_success.json"
    dependsOn:
      activities:
      - name: "app01_2_rd"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "Stop_SqlServerStoredProcedure"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_export_app01_2_rd_main/activities/Stop_SqlServerStoredProcedure/Stop_SqlServerStoredProcedure.json"
    dependsOn:
      activities:
      - name: "BLM2Blob_success"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "BLM2Blob_Failed"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_export_app01_2_rd_main/activities/BLM2Blob_Failed/BLM2Blob_Failed.json"
    dependsOn:
      activities:
      - name: "app01_2_rd"
        dependencyConditions:
        - "failed"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "app01_2_rd"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_export_app01_2_rd_main/activities/app01_2_rd/app01_2_rd.json"
    dependsOn:
      activities:
      - name: "Set_fileName_increse_copy"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 300000
      timeoutSeconds: 604800
  - name: "Set_partition_date"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "partition_date"
    value:
      rawValue: "@if(equals(pipeline().parameters.partition_date,'0'),formatDateTime(addhours(utcnow(),\
        \ 8), 'yyyy-MM-dd'),pipeline().parameters.partition_date)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Start_SqlServerStoredProcedure"
        dependencyConditions:
        - "succeeded"
  - name: "Set_Directory_increse_copy"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "Directory"
    value:
      rawValue: "@concat('iccid/',substring(variables('partition_date'),0,4),'/',substring(variables('partition_date'),5,2),'/',substring(variables('partition_date'),8,2))"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Set_endDate"
        dependencyConditions:
        - "succeeded"
  - name: "Set_fileName_increse_copy"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "FileName"
    value:
      rawValue: "@concat('ICCID_INCREASE_',replace(variables('partition_date'),'-',''),'.csv')"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Set_Directory_increse_copy"
        dependencyConditions:
        - "succeeded"
  - name: "Set_startDate"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "startDate"
    value:
      rawValue: "@formatDateTime(adddays(variables('partition_date'),-18),'yyyy-MM-dd')"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Set_partition_date"
        dependencyConditions:
        - "succeeded"
  - name: "Set_endDate"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "endDate"
    value:
      rawValue: "@formatDateTime(adddays(variables('partition_date'),-3),'yyyy-MM-dd')"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Set_startDate"
        dependencyConditions:
        - "succeeded"
  - name: "CheckTriggerType"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "@Or(Equals(pipeline().TriggerType,'Manual'),Equals(pipeline().parameters.MainPipelineTriggerType,\
        \ 'Manual'))"
      op: "EQUAL_TO"
      right: "true"
  - name: "SetJobNameManual"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@concat('$M$_', 'exp_app01_2_rd')"
    outputVariables: []
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "SetJobNameAuto"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "exp_app01_2_rd"
    outputVariables: []
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "Delete_temp_folder"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_export_app01_2_rd_main/activities/Delete_temp_folder/Delete_temp_folder.json"
    dependsOn:
      activities:
      - name: "app01_2_rd"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  parameters:
  - name: "LogEnabled"
    default: "1"
  - name: "partition_date"
    default: "0"
  - name: "DatabaseName"
    default: "app01_2_rd"
  - name: "TableName"
    default: "exp_app01_2_rd"
  - name: "MainPipelineTriggerType"
    default: ""
  variables:
  - name: "frameworkParameters"
    default: ""
  - name: "logInRunningLogAsSubPipeline"
    default: ""
  - name: "Container"
    default: "sending-zone"
  - name: "Directory"
    default: ""
  - name: "FileName"
    default: ""
  - name: "partition_date"
    default: ""
  - name: "startDate"
    default: ""
  - name: "endDate"
    default: ""
  - name: "JobNameVar"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
