apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "pl_dmp_oneapp_community_content_sqs"
spec:
  displayName: "pl_dmp_oneapp_community_content_sqs"
  description: "050094b5-0000-4200-0000-69e5d7440000"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
    frequency: "daily"
  activities:
  - name: "Content_recommendation_to_SQS"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_community_content_sqs/activities/Content_recommendation_to_SQS/Content_recommendation_to_SQS.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "new_emr_queue_20260527140648-notebook_test"
    computingResourceGroupName: "vke192"
    computingResourceGroupId: 1099
    sparkConf:
    - key: "serverless.spark.access.key"
      value: "{{ak}}"
    - key: "serverless.spark.secret.key"
      value: "{{sk}}"
    executeParam:
      image:
        imageUrl: "image-repo-cn-beijing.cr.volces.com/emr-serverless-spark/spark:3.5.1-py3.12-ubuntu20.04-802"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 0
      maxRetries: 100
      minRetryIntervalSeconds: 0
  parameters:
  - name: "Mode"
    default: "Print"
  - name: "Profile"
    default: "Dev"
  - name: "run_date"
    default: ""
  schedulingResourceGroupName: "exclusive_schedule"
  schedulingResourceGroupId: 1302
  dependsOn:
    pipelines: []
    self:
      enabled: false
