apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "863b7070d5d03d85fbdc4d039652db4b"
spec:
  displayName: "pl_dmp_oneapp_community_content_sqs"
  description: "050094b5-0000-4200-0000-69e5d7440000"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "Content_recommendation_to_SQS"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/User/demo/etl_pipeline/pl_dmp_oneapp_community_content_sqs/activities/Content_recommendation_to_SQS/Content_recommendation_to_SQS.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
