apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "ed441ab76769155f144730faed600b4b"
spec:
  displayName: "pl_dbrs_job_ingst_app01_mysql_source_02_union_detail"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "StartLogRecord"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_ingst_app01_mysql_source_02_union_detail/activities/StartLogRecord/StartLogRecord.json"
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "Copy2RawData"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_ingst_app01_mysql_source_02_union_detail/activities/Copy2RawData/Copy2RawData.json"
    dependsOn:
      activities:
      - name: "Set_sourcesql"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 2
      minRetryIntervalMillis: 600000
      timeoutSeconds: 7200
  - name: "If_Condition1"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "@Or(Equals(pipeline().TriggerType,'Manual'),Equals(pipeline().parameters.MainPipelineTriggerType,\
        \ 'Manual'))"
      op: "EQUAL_TO"
      right: "true"
  - name: "Manual"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@concat('$M$_', pipeline().parameters.TableName)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "Auto"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@pipeline().parameters.TableName"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "Rowsql"
    type: "look_up"
    dataSource: "pl_dbrs_job_dealers_ingst_otrplus_union_main1_support_live_sanitized__ls_asql_infra_03"
    table: "DaimlerDatabricksADFControlTable_app01_dealer"
    dependsOn:
      activities:
      - name: "Copy_dealer_id_data"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 300000
      timeoutSeconds: 3600
  - name: "Copy_dealer_id_data"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_ingst_app01_mysql_source_02_union_detail/activities/Copy_dealer_id_data/Copy_dealer_id_data.json"
    dependsOn:
      activities:
      - name: "Set_SrcTableName"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 30000
      timeoutSeconds: 3600
  - name: "Set_sourcesql"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "source_sql"
    value:
      rawValue: "@replace(replace(replace(replace(concat(substring(string(activity('Rowsql').output.value),\
        \ 6, add(lastindexof(string(activity('Rowsql').output.value),'union all'),-6))),'&gt;','>'),'&lt;','<'),'last_mdf_dt\
        \ ,','last_mdf_dt ,'''),' dealer_id_partition',''' dealer_id_partition')"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Rowsql"
        dependencyConditions:
        - "succeeded"
  - name: "Set_SrcDatabaseName"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "SrcDatabaseName"
    value:
      rawValue: "@split(replace(pipeline().parameters.DataSourceSQL_FROM, 'from ',\
        \ ''), '.')[0]"
    outputVariables: []
    dependsOn:
      activities:
      - name: "StartLogRecord"
        dependencyConditions:
        - "succeeded"
  - name: "Set_SrcTableName"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "SrcTableName"
    value:
      rawValue: "@split(replace(pipeline().parameters.DataSourceSQL_FROM, 'from ',\
        \ ''), '.')[1]"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Set_SrcDatabaseName"
        dependencyConditions:
        - "succeeded"
  parameters:
  - name: "pStartDate"
    default: ""
  - name: "pEndDate"
    default: ""
  - name: "logEnabled"
    default: "1"
  - name: "PartitionID"
    default: ""
  - name: "pl_name"
    default: ""
  - name: "MainPipelineTriggerType"
    default: ""
  - name: "DataSourceSQL_FROM"
    default: ""
  - name: "DatabaseName"
    default: ""
  - name: "DataSourceSQL"
    default: ""
  - name: "TableName"
    default: ""
  variables:
  - name: "JobNameVar"
    default: ""
  - name: "SrcDatabaseName"
    default: ""
  - name: "SrcTableName"
    default: ""
  - name: "source_sql"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
