apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "2517558bf295502312ef0c8b537eb101"
spec:
  displayName: "pl_dbrs_fix_ingst_tireo2opost_main_support_live_sanitized__pl_dbrs_fix_ingst_app01_main"
  runAs: "Account/2100052957"
  trigger:
    type: "SCHEDULED"
    pauseStatus: "UNPAUSED"
    frequency: "daily"
    cronExpression: "0 30 3 * * ?"
    priority: "d5"
  activities:
  - name: "SetPartitionID"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "pt"
    value:
      rawValue: "@if(equals(pipeline().parameters.partition_date,null),formatDateTime(adddays(addhours(utcnow(),8),-1),'yyyy-MM-dd'),pipeline().parameters.partition_date)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "RowDataCount"
    type: "look_up"
    dataSource: "ls_psql_tireo2o_servicemall_new"
    table: "ds_psql_tireo2o_servicemall"
    dependsOn:
      activities:
      - name: "SetPartitionID"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "RowCountGreaterZero"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "{{activity('RowDataCount').output.firstrow.cnt}}"
      op: "GREATER_THAN"
      right: "0"
    dependsOn:
      activities:
      - name: "RowDataCount"
        dependencyConditions:
        - "succeeded"
  - name: "source2raw"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_tireo2opost_main_support_live_sanitized__pl_dbrs_fix_ingst_app01_main/activities/source2raw/source2raw.json"
    dependsOn:
      activities:
      - name: "RowCountGreaterZero"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 600000
      timeoutSeconds: 10800
  - name: "pl_dbrs_fix_ingst_app01_detail"
    type: "execute_pipeline"
    pipelineName: "pl_dbrs_fix_ingst_tireo2opost_main_support_live_sanitized__pl_dbrs_fix_ingst_app01_detail"
    pipelineId: "130e9e7cca29ada0cc6b6fcb3404141d"
    projectId: "10926"
    bizDate: "${DATE}"
    pipelineParameterValues:
      tables: ""
      pt: ""
      LogEnabled: ""
      MainPipelineTriggerType: ""
      DatabaseName: ""
      TableName: ""
      is_header: ""
      dir_prefix: ""
      storage_account: ""
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "source2stg"
        dependencyConditions:
        - "succeeded"
      - name: "RowCountGreaterZero"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "source2stg"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_tireo2opost_main_support_live_sanitized__pl_dbrs_fix_ingst_app01_main/activities/source2stg/source2stg.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "source2raw"
        dependencyConditions:
        - "succeeded"
      - name: "RowCountGreaterZero"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "Wait1SecondandFinish"
    type: "wait"
    waitTimeInSeconds: 1
    dependsOn:
      activities:
      - name: "RowCountGreaterZero"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "Env"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "Env"
    value:
      rawValue: "@pipeline().globalParameters.Environment"
    outputVariables: []
  - name: "If_Condition1"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "{{pipeline.vars.Env}}"
      op: "EQUAL_TO"
      right: "INT"
    dependsOn:
      activities:
      - name: "Env"
        dependencyConditions:
        - "succeeded"
  - name: "container_INT"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "dir_prefix"
    value:
      rawValue: "<<REDACTED>>"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "storage_account_INT"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "storage_account"
    value:
      rawValue: "<<REDACTED>>"
    outputVariables: []
    dependsOn:
      activities:
      - name: "container_INT"
        dependencyConditions:
        - "succeeded"
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "container_prod"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "dir_prefix"
    value:
      rawValue: "<<REDACTED>>"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "storage_account_prod"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "storage_account"
    value:
      rawValue: "<<REDACTED>>"
    outputVariables: []
    dependsOn:
      activities:
      - name: "container_prod"
        dependencyConditions:
        - "succeeded"
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: false
  parameters:
  - name: "LogEnabled"
    default: "1"
  - name: "partition_date"
    default: ""
  - name: "tables"
    default: "ALL"
  - name: "DatabaseName"
    default: "bz_cn_dl.rawdata_tireo2o"
  - name: "TableName"
    default: "rw_dealer_tireo2o_throw_account_log"
  - name: "is_header"
    default: "False"
  variables:
  - name: "pt"
    default: ""
  - name: "logInRunningLogAsSubPipeline"
    default: ""
  - name: "Env"
    default: ""
  - name: "dir_prefix"
    default: ""
  - name: "storage_account"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
