apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "d553022c86b9ab8fa0ab0780baa2bf7c"
spec:
  displayName: "pl_dbrs_fix_ingst_app01_blob_main"
  runAs: "Account/2100052957"
  trigger:
    type: "SCHEDULED"
    pauseStatus: "UNPAUSED"
    frequency: "daily"
    cronExpression: "0 0 11 * * ?"
    priority: "d5"
  activities:
  - name: "GetJobList"
    type: "look_up"
    dataSource: "pl_dbrs_fix_ingst_media_blob_main_support_live_sanitized__ls_asql_infra_05"
    table: "<<REDACTED>>"
    dependsOn:
      activities:
      - name: "Set_filePartitionID"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "source2raw"
    type: "for_each"
    items: "@activity('GetJobList').output.value"
    concurrency: 5
    activities:
    - name: "pl_dbrs_fix_ingst_app01_blob_detail_item"
      type: "execute_pipeline"
      pipelineName: "pl_dbrs_fix_ingst_app01_blob_detail_item"
      pipelineId: "61c449ff69d5e11487f0aeb0cf6571d9"
      projectId: "10926"
      bizDate: "${DATE}"
      pipelineParameterValues:
        File: ""
        LandingDirectory: ""
        DatabaseName: ""
        PartitionID: ""
        LogEnabled: ""
        MainPipelineTriggerType: ""
        env_storage: ""
        TableName: ""
        DestPartitionColumnName: ""
        containers: ""
        is_header: ""
      waitingSuccess: true
    dependsOn:
      activities:
      - name: "GetJobList"
        dependencyConditions:
        - "succeeded"
  - name: "SetPartitionID"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "PartitionID"
    value:
      rawValue: "@if(equals(pipeline().parameters.pt,null),formatDateTime(addhours(utcnow(),8),'yyyy-MM-dd'),pipeline().parameters.pt)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Set_variable1"
        dependencyConditions:
        - "succeeded"
  - name: "GetEnv"
    type: "look_up"
    dataSource: "pl_dbrs_fix_ingst_media_blob_main_support_live_sanitized__ls_asql_infra_05"
    table: "pl_dbrs_fix_ingst_media_blob_main_support_live_sanitized__ds_asql_conf_environment"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "Set_variable1"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "env_storage"
    value:
      rawValue: "@activity('GetEnv').output.firstrow.env_storage"
    outputVariables: []
    dependsOn:
      activities:
      - name: "GetEnv"
        dependencyConditions:
        - "succeeded"
  - name: "Set_filePartitionID"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "filePartitionID"
    value:
      rawValue: "@if(equals(pipeline().parameters.filePartitionID,null),formatDateTime(addhours(utcnow(),8),'yyyyMMdd'),pipeline().parameters.filePartitionID)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "SetPartitionID"
        dependencyConditions:
        - "succeeded"
  - name: "Delete_lake_source_file"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_main/activities/Delete_lake_source_file/Delete_lake_source_file.json"
    dependsOn:
      activities:
      - name: "source2raw"
        dependencyConditions:
        - "completed"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "Get_social_bbdo_Metadata"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_main/activities/Get_social_bbdo_Metadata/Get_social_bbdo_Metadata.json"
    dependsOn:
      activities:
      - name: "source2raw"
        dependencyConditions:
        - "completed"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "ForEach_social_bbdo"
    type: "for_each"
    items: "@activity('Get social bbdo Metadata').output.childItems"
    concurrency: 1
    activities:
    - name: "check_social_bbdo_file_name"
      type: "if_condition"
      description: "Conditional execution"
      condition:
        type: "BINARY_OP"
        left: "@if(endswith(item().name,'csv'),if(greater(length(item().name),13),contains('Social_Data_Template_Content_Followers_KOL_Weekly_AMG_[partition_date].csv,Social_Data_Template_Content_Followers_KOL_Weekly_DOUYIN_[partition_date].csv,Social_Data_Template_Content_OfficialAccount_Weekly_AMG_[partition_date].csv,Social_Data_Template_Content_OfficialAccount_Weekly_DOUYIN_[partition_date].csv,Social_Data_Template_Followers_OfficialAccount_Daily_AMG_[partition_date].csv,Social_Data_Template_Followers_OfficialAccount_Daily_DOUYIN_[partition_date].csv',substring(item().name,0,add(length(item().name),-13))),'false'),'false')"
        op: "EQUAL_TO"
        right: "true"
    - name: "set_social_bbdo_error_file_name"
      type: "custom"
      source: "WORKSPACE"
      path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_main/activities/set_social_bbdo_error_file_name/set_social_bbdo_error_file_name.json"
      dependsOn:
        activities:
        - name: "check_social_bbdo_file_name"
          dependencyConditions:
          - "succeeded"
          outcome: false
      retryPolicy:
        maxRetries: 0
        minRetryIntervalMillis: 30000
        timeoutSeconds: 604800
    dependsOn:
      activities:
      - name: "Get_social_bbdo_Metadata"
        dependencyConditions:
        - "succeeded"
  - name: "Get_social_ogilvy_Metadata"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_main/activities/Get_social_ogilvy_Metadata/Get_social_ogilvy_Metadata.json"
    dependsOn:
      activities:
      - name: "source2raw"
        dependencyConditions:
        - "completed"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "Get_mediabuy_Metadata"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_main/activities/Get_mediabuy_Metadata/Get_mediabuy_Metadata.json"
    dependsOn:
      activities:
      - name: "source2raw"
        dependencyConditions:
        - "completed"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "ForEach_socia_ogilvy"
    type: "for_each"
    items: "@activity('Get social ogilvy Metadata').output.childItems"
    concurrency: 1
    activities:
    - name: "check_social_ogilvy_file_name"
      type: "if_condition"
      description: "Conditional execution"
      condition:
        type: "BINARY_OP"
        left: "@if(endswith(item().name,'csv'),if(greater(length(item().name),13),contains('Social_Data_Template_Followers_OfficialAccount_Daily_[partition_date].csv,Social_Data_Template_Content_OfficialAccount_Weekly_[partition_date].csv,Social_Data_Template_Content_Followers_KOL_Weekly_[partition_date].csv',substring(item().name,0,add(length(item().name),-13))),'false'),'false')"
        op: "EQUAL_TO"
        right: "true"
    - name: "set_error_social_ogilvy_file_name"
      type: "custom"
      source: "WORKSPACE"
      path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_main/activities/set_error_social_ogilvy_file_name/set_error_social_ogilvy_file_name.json"
      dependsOn:
        activities:
        - name: "check_social_ogilvy_file_name"
          dependencyConditions:
          - "succeeded"
          outcome: false
      retryPolicy:
        maxRetries: 0
        minRetryIntervalMillis: 30000
        timeoutSeconds: 604800
    dependsOn:
      activities:
      - name: "Get_social_ogilvy_Metadata"
        dependencyConditions:
        - "succeeded"
  - name: "ForEach_mediabuy"
    type: "for_each"
    items: "@activity('Get mediabuy Metadata').output.childItems"
    concurrency: 1
    activities:
    - name: "check__mediabuy_file_name"
      type: "if_condition"
      description: "Conditional execution"
      condition:
        type: "BINARY_OP"
        left: "@if(endswith(item().name,'csv'),if(startswith(item().name,'ODP_app01_Data_Template_by_app01_Type_datalake.'),'true','false'),'false')"
        op: "EQUAL_TO"
        right: "true"
    - name: "set_error_mediabuy_file_name"
      type: "custom"
      source: "WORKSPACE"
      path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_main/activities/set_error_mediabuy_file_name/set_error_mediabuy_file_name.json"
      dependsOn:
        activities:
        - name: "check__mediabuy_file_name"
          dependencyConditions:
          - "succeeded"
          outcome: false
      retryPolicy:
        maxRetries: 0
        minRetryIntervalMillis: 30000
        timeoutSeconds: 604800
    dependsOn:
      activities:
      - name: "Get_mediabuy_Metadata"
        dependencyConditions:
        - "succeeded"
  parameters:
  - name: "LogEnabled"
    default: "1"
  - name: "pt"
    default: ""
  - name: "pTableList"
    default: ""
  - name: "filePartitionID"
    default: ""
  - name: "is_header"
    default: "False"
  variables:
  - name: "PartitionID"
    default: ""
  - name: "env_storage"
    default: ""
  - name: "filePartitionID"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
