apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "57de9c4d3de2c70a735b122f7d673254"
spec:
  displayName: "pl_dmp_oneapp_community_recommender_ranking_parallel"
  description: "050090b5-0000-4200-0000-69e5d7440000"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "Set_run_date"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "run_date"
    value:
      rawValue: "@pipeline().parameters.run_date"
    outputVariables: []
  - name: "process_ranker_data"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/User/demo/etl_pipeline/pl_dmp_oneapp_community_recommender_ranking_parallel/activities/process_ranker_data/process_ranker_data.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "Set_run_date"
        dependencyConditions:
        - "succeeded"
  - name: "Train_ranking_model"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/User/demo/etl_pipeline/pl_dmp_oneapp_community_recommender_ranking_parallel/activities/Train_ranking_model/Train_ranking_model.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "process_ranker_data"
        dependencyConditions:
        - "succeeded"
  - name: "Run_ranking_shards"
    type: "for_each"
    items: "@split(pipeline().parameters.parallel_shard_ids, ',')"
    concurrency: 5
    activities:
    - name: "Run_ranking_model_shard"
      type: "notebook"
      description: "A new Notebook job"
      source: "WORKSPACE"
      path: "/Workspace/User/demo/etl_pipeline/pl_dmp_oneapp_community_recommender_ranking_parallel/activities/Run_ranking_model_shard/Run_ranking_model_shard.ipynb"
      kernelType: "emr_serverless_spark_python"
      engineQueue: "公共队列-Default"
      computingResourceGroupName: "public_compute"
      computingResourceGroupId: 1012
      sparkConf: []
      executeParam:
        image:
          imageUrl: ""
      parameters: []
      resources: []
    dependsOn:
      activities:
      - name: "Train_ranking_model"
        dependencyConditions:
        - "succeeded"
  - name: "Merge_ranking_shards"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/User/demo/etl_pipeline/pl_dmp_oneapp_community_recommender_ranking_parallel/activities/Merge_ranking_shards/Merge_ranking_shards.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "Run_ranking_shards"
        dependencyConditions:
        - "succeeded"
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
