apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "61c449ff69d5e11487f0aeb0cf6571d9"
spec:
  displayName: "pl_dbrs_fix_ingst_app01_blob_detail_item"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "Get_Metadata"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_detail_item/activities/Get_Metadata/Get_Metadata.json"
    dependsOn:
      activities:
      - name: "StartLogRecord"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "ForEach"
    type: "for_each"
    items: "@activity('Get Metadata').output.childItems"
    concurrency: 1
    activities:
    - name: "If_Condition1"
      type: "if_condition"
      description: "Conditional execution"
      condition:
        type: "BINARY_OP"
        left: "@contains(item().name,substring(pipeline().parameters.file,0,add(lastindexof(pipeline().parameters.file,'.csv'),-9)))"
        op: "EQUAL_TO"
        right: "true"
    - name: "Set_PartitionID"
      type: "set_variable"
      description: "Set a pipeline variable"
      variableType: "PIPELINE_INNER"
      variableName: "PartitionID"
      value:
        rawValue: "@if(contains(item().name,'ODP_app01_Data_Template_by_app01_Type_datalake'),concat(substring(split(item().name,\
          \ '.')[1],0,4),'-',substring(split(item().name, '.')[1],4,2),'-',substring(split(item().name,\
          \ '.')[1],6,add(length(split(item().name, '.')[1]),-6))),concat(substring(item().name,add(lastindexof(item().name,'.csv'),-8),4),'-',substring(item().name,add(lastindexof(item().name,'.csv'),-4),2),'-',substring(item().name,add(lastindexof(item().name,'.csv'),-2),2)))"
      outputVariables: []
      dependsOn:
        activities:
        - name: "If_Condition1"
          dependencyConditions:
          - "succeeded"
          outcome: true
    - name: "pl_dbrs_fix_ingst_app01_blob_detail"
      type: "execute_pipeline"
      pipelineName: "pl_dbrs_fix_ingst_app01_blob_detail"
      pipelineId: "dee57c50d2feac70e95d45f8714c56bb"
      projectId: "10926"
      bizDate: "${DATE}"
      pipelineParameterValues:
        File: ""
        LandingDirectory: ""
        DatabaseName: ""
        PartitionID: ""
        LogEnabled: "1"
        MainPipelineTriggerType: ""
        env_storage: ""
        TableName: ""
        DestPartitionColumnName: ""
        containers: ""
        ParentPiplineRunID: ""
        is_header: ""
      waitingSuccess: true
      dependsOn:
        activities:
        - name: "If_Condition1"
          dependencyConditions:
          - "succeeded"
          outcome: true
    - name: "Set_file"
      type: "set_variable"
      description: "Set a pipeline variable"
      variableType: "PIPELINE_INNER"
      variableName: "File"
      value:
        rawValue: "@item().name"
      outputVariables: []
      dependsOn:
        activities:
        - name: "If_Condition1"
          dependencyConditions:
          - "succeeded"
          outcome: true
    - name: "set_pipeline_error_file_name"
      type: "custom"
      source: "WORKSPACE"
      path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_detail_item/activities/set_pipeline_error_file_name/set_pipeline_error_file_name.json"
      dependsOn:
        activities:
        - name: "If_Condition1"
          dependencyConditions:
          - "succeeded"
          outcome: true
      retryPolicy:
        maxRetries: 0
        minRetryIntervalMillis: 30000
        timeoutSeconds: 604800
    dependsOn:
      activities:
      - name: "Get_Metadata"
        dependencyConditions:
        - "succeeded"
  - name: "CheckTriggerType"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "@Or(Equals(pipeline().TriggerType,'Manual'),Equals(pipeline().parameters.MainPipelineTriggerType,\
        \ 'Manual'))"
      op: "EQUAL_TO"
      right: "true"
  - name: "SetJobNameManual"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@concat('$M$_', pipeline().parameters.TableName)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "SetJobNameAuto"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@pipeline().parameters.TableName"
    outputVariables: []
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "StartLogRecord"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_detail_item/activities/StartLogRecord/StartLogRecord.json"
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "Log_Check_Hive_Count_Fail"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_detail_item/activities/Log_Check_Hive_Count_Fail/Log_Check_Hive_Count_Fail.json"
    dependsOn:
      activities:
      - name: "ForEach"
        dependencyConditions:
        - "failed"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "Log_Copy_To_Hive_Success"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_blob_detail_item/activities/Log_Copy_To_Hive_Success/Log_Copy_To_Hive_Success.json"
    dependsOn:
      activities:
      - name: "ForEach"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  parameters:
  - name: "File"
    default: "ODP_app01_Data_Template_by_app01_Type_datalake"
  - name: "LandingDirectory"
    default: "landingzone/bmbs/"
  - name: "DatabaseName"
    default: "rawdata_app01"
  - name: "PartitionID"
    default: "2019-07-04"
  - name: "LogEnabled"
    default: "1"
  - name: "MainPipelineTriggerType"
    default: ""
  - name: "env_storage"
    default: ""
  - name: "TableName"
    default: ""
  - name: "DestPartitionColumnName"
    default: "partition_date"
  - name: "containers"
    default: ""
  - name: "is_header"
    default: ""
  variables:
  - name: "LastMdfDt"
    default: ""
  - name: "JobNameVar"
    default: ""
  - name: "PartitionID"
    default: ""
  - name: "File"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
