apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "pl_dmp_oneapp_store_recommender_v2_mmc_data_update"
spec:
  displayName: "pl_dmp_oneapp_store_recommender_v2_mmc_data_update"
  description: "150013e3-0000-4200-0000-69ef2e4c0000"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
    frequency: "daily"
  activities:
  - name: "Set_run_date"
    type: "set_variable"
    description: "Set a pipeline variable\nSource: platform=adf, activity type=SetVariable"
    variableType: "PIPELINE_INNER"
    variableName: "run_date"
    value:
      rawValue: "{{pipeline.params.run_date}}"
    outputVariables: []
  - name: "User_product_attributes_and_interactions"
    type: "notebook"
    description: "A new Notebook job\nSource: platform=adf, activity type=DatabricksNotebook"
    source: "WORKSPACE"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_store_recommender_v2_mmc_data_update/activities/User_product_attributes_and_interactions/User_product_attributes_and_interactions.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "new_emr_queue_20260527140648-notebook_test"
    computingResourceGroupName: "vke192"
    computingResourceGroupId: 1099
    sparkConf:
    - key: "serverless.spark.access.key"
      value: "{{ak}}"
    - key: "serverless.spark.secret.key"
      value: "{{sk}}"
    executeParam:
      image:
        imageUrl: "image-repo-cn-beijing.cr.volces.com/emr-serverless-spark/spark:3.5.1-py3.12-ubuntu20.04-802"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    dependsOn:
      activities:
      - name: "Set_run_date"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 0
      maxRetries: 100
      minRetryIntervalSeconds: 0
  - name: "bottom_features"
    type: "notebook"
    description: "A new Notebook job\nSource: platform=adf, activity type=DatabricksNotebook"
    source: "WORKSPACE"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_store_recommender_v2_mmc_data_update/activities/bottom_features/bottom_features.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "new_emr_queue_20260527140648-notebook_test"
    computingResourceGroupName: "vke192"
    computingResourceGroupId: 1099
    sparkConf:
    - key: "serverless.spark.access.key"
      value: "{{ak}}"
    - key: "serverless.spark.secret.key"
      value: "{{sk}}"
    executeParam:
      image:
        imageUrl: "image-repo-cn-beijing.cr.volces.com/emr-serverless-spark/spark:3.5.1-py3.12-ubuntu20.04-802"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    dependsOn:
      activities:
      - name: "User_product_attributes_and_interactions"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 0
      maxRetries: 100
      minRetryIntervalSeconds: 0
  parameters:
  - name: "table_config_path"
    default: ""
  - name: "model_config_path"
    default: ""
  - name: "run_date"
    default: ""
  variables:
  - name: "run_date"
    default: ""
  schedulingResourceGroupName: "exclusive_schedule"
  schedulingResourceGroupId: 1302
  dependsOn:
    pipelines: []
    self:
      enabled: false
