apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "afceca88f7e86db1e39b939bf323c6ec"
spec:
  displayName: "pl_dbrs_fix_ingst_app01_asql_evt_main1"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "partitionMonth"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "partition_month"
    value:
      rawValue: "@split(pipeline().parameters.sourceFile,'.')[0]"
    outputVariables: []
    dependsOn:
      activities:
      - name: "notify_job_start"
        dependencyConditions:
        - "succeeded"
  - name: "partitionTIme"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "partition_time"
    value:
      rawValue: "@split(pipeline().parameters.sourceFile,'.')[2]"
    outputVariables: []
    dependsOn:
      activities:
      - name: "typeName"
        dependencyConditions:
        - "succeeded"
  - name: "typeName"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "type_name"
    value:
      rawValue: "@split(pipeline().parameters.sourceFile,'.')[1]"
    outputVariables: []
    dependsOn:
      activities:
      - name: "partitionMonth"
        dependencyConditions:
        - "succeeded"
  - name: "If_Condition1"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "{{activity('check_falg_file').output.firstRow.countResult}}"
      op: "EQUAL_TO"
      right: "1"
    dependsOn:
      activities:
      - name: "check_falg_file"
        dependencyConditions:
        - "succeeded"
  - name: "pl_dbrs_fix_ingst_app01_asql_evt_main2"
    type: "execute_pipeline"
    pipelineName: "pl_dbrs_fix_ingst_app01_asql_evt_main2"
    pipelineId: "fd798a096d7e0d5cefeaf15d36683e2e"
    projectId: "10926"
    bizDate: "${DATE}"
    pipelineParameterValues:
      partition_month: ""
      partition_time: ""
      type_name: ""
      sourceFile: ""
      env: ""
      TableName: ""
      DatabaseName: "bz_cn_dl.datalake_app01"
      MainPipelineTriggerType: ""
      is_header: ""
    waitingSuccess: true
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "send_email"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_asql_evt_main1/activities/send_email/send_email.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: false
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 240000
      timeoutSeconds: 43200
  - name: "check_falg_file"
    type: "look_up"
    dataSource: "pl_dbrs_fix_ingst_nbis_asql_evt_main1_support_live_sanitized__ls_asql_infra_05"
    table: "ds_msc_asql_controltable_app01"
    dependsOn:
      activities:
      - name: "partitionTIme"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 2
      minRetryIntervalMillis: 120000
      timeoutSeconds: 43200
  - name: "notify_job_start"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_asql_evt_main1/activities/notify_job_start/notify_job_start.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "Set_Env"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 120000
      timeoutSeconds: 43200
  - name: "Set_Env"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "env"
    value:
      rawValue: "@pipeline().globalParameters.Environment"
    outputVariables: []
  parameters:
  - name: "sourceFolder"
    default: ""
  - name: "sourceFile"
    default: "202307.Retail Target.20230809105536619.PUBLISHED"
  - name: "is_header"
    default: "False"
  variables:
  - name: "partition_month"
    default: ""
  - name: "partition_time"
    default: ""
  - name: "type_name"
    default: ""
  - name: "env"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
