apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "pl_dmp_oneapp_store_recommender_v2_mmc_inference_parallel"
spec:
  displayName: "pl_dmp_oneapp_store_recommender_v2_mmc_inference_parallel"
  description: "150016e3-0000-4200-0000-69ef2e4c0000"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
    frequency: "daily"
  activities:
  - name: "Set_run_date"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "run_date"
    value:
      rawValue: "{{pipeline.params.run_date}}"
    outputVariables: []
  - name: "Run_ranking_shards"
    type: "for_each"
    items: "{{pipeline.params.parallel_shard_ids}}"
    concurrency: 5
    activities:
    - name: "Run_ranking_model_shard"
      type: "notebook"
      description: "A new Notebook job"
      source: "WORKSPACE"
      path: "/Workspace/newide_repos/pl_dmp_oneapp_store_recommender_v2_mmc_inference_parallel/activities/Run_ranking_model_shard/Run_ranking_model_shard.ipynb"
      kernelType: "emr_serverless_spark_python"
      engineQueue: "new_emr_queue_20260527140648-notebook_test"
      computingResourceGroupName: "vke192"
      computingResourceGroupId: 1099
      sparkConf:
      - key: "serverless.spark.access.key"
        value: "{{ak}}"
      - key: "serverless.spark.secret.key"
        value: "{{sk}}"
      executeParam:
        image:
          imageUrl: "image-repo-cn-beijing.cr.volces.com/emr-serverless-spark/spark:3.5.1-py3.12-ubuntu20.04-802"
        cpuCores: 1
        memoryMb: 4096
      parameters:
      - name: "num_shards"
        default: ""
      - name: "table_config_path"
        default: ""
      - name: "infer_config_path"
        default: ""
      - name: "shard_id"
        default: ""
      - name: "model_config_path"
        default: ""
      - name: "shard_id_base"
        default: ""
      - name: "run_date"
        default: ""
      resources: []
      position:
        x: -110
        "y": 0
      retryPolicy:
        retryOnTimeout: true
        timeoutSeconds: 0
        maxRetries: 100
        minRetryIntervalSeconds: 0
      parameterValues:
        num_shards: "{{pipeline.params.parallel_shard_count}}"
        table_config_path: "{{pipeline.params.table_config_path}}"
        infer_config_path: "{{pipeline.params.infer_config_path}}"
        shard_id: "{{items.each}}"
        model_config_path: "{{pipeline.params.model_config_path}}"
        shard_id_base: "{{pipeline.params.parallel_shard_id_base}}"
        run_date: "{{pipeline.vars.run_date}}"
    dependsOn:
      activities:
      - name: "Create_candidate_set"
        dependencyConditions:
        - "succeeded"
  - name: "Merge_ranking_shards"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_store_recommender_v2_mmc_inference_parallel/activities/Merge_ranking_shards/Merge_ranking_shards.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "new_emr_queue_20260527140648-notebook_test"
    computingResourceGroupName: "vke192"
    computingResourceGroupId: 1099
    sparkConf:
    - key: "serverless.spark.access.key"
      value: "{{ak}}"
    - key: "serverless.spark.secret.key"
      value: "{{sk}}"
    executeParam:
      image:
        imageUrl: "image-repo-cn-beijing.cr.volces.com/emr-serverless-spark/spark:3.5.1-py3.12-ubuntu20.04-802"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    dependsOn:
      activities:
      - name: "Run_ranking_shards"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 0
      maxRetries: 100
      minRetryIntervalSeconds: 0
  - name: "Create_candidate_set"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/newide_repos/pl_dmp_oneapp_store_recommender_v2_mmc_inference_parallel/activities/Create_candidate_set/Create_candidate_set.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "new_emr_queue_20260527140648-notebook_test"
    computingResourceGroupName: "vke192"
    computingResourceGroupId: 1099
    sparkConf:
    - key: "serverless.spark.access.key"
      value: "{{ak}}"
    - key: "serverless.spark.secret.key"
      value: "{{sk}}"
    executeParam:
      image:
        imageUrl: "image-repo-cn-beijing.cr.volces.com/emr-serverless-spark/spark:3.5.1-py3.12-ubuntu20.04-802"
      cpuCores: 1
      memoryMb: 4096
    parameters: []
    resources: []
    position:
      x: -110
      "y": 0
    dependsOn:
      activities:
      - name: "Set_run_date"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      retryOnTimeout: true
      timeoutSeconds: 0
      maxRetries: 100
      minRetryIntervalSeconds: 0
  parameters:
  - name: "parallel_shard_count"
    default: "4"
  - name: "parallel_shard_ids"
    default: "0,1,2,3"
  - name: "parallel_batch_count"
    default: "4"
  - name: "table_config_path"
    default: ""
  - name: "infer_config_path"
    default: ""
  - name: "model_config_path"
    default: ""
  - name: "parallel_shard_id_base"
    default: "0"
  - name: "run_date"
    default: ""
  variables:
  - name: "run_date"
    default: ""
  schedulingResourceGroupName: "exclusive_schedule"
  schedulingResourceGroupId: 1302
  dependsOn:
    pipelines: []
    self:
      enabled: false
