apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "874878e911ad28a5d74570cd4c8f2168"
spec:
  displayName: "pl_dbrs_job_ingst_s3_app01_detail"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "StartLogRecord"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_ingst_s3_app01_detail/activities/StartLogRecord/StartLogRecord.json"
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "source2raw_fail"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_ingst_s3_app01_detail/activities/source2raw_fail/source2raw_fail.json"
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "failed"
        outcome: false
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "CheckTriggerType"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "@Or(Equals(pipeline().TriggerType,'Manual'),Equals(pipeline().parameters.MainPipelineTriggerType,\
        \ 'Manual'))"
      op: "EQUAL_TO"
      right: "true"
  - name: "SetJobNameManual"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@concat('$M$_', pipeline().parameters.TableName)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "SetJobNameAuto"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@pipeline().parameters.TableName"
    outputVariables: []
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "If_Condition1"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "{{pipeline.params.TableName}}"
      op: "EQUAL_TO"
      right: "rw_part_tireo2o_e12_wallbox"
    dependsOn:
      activities:
      - name: "StartLogRecord"
        dependencyConditions:
        - "succeeded"
  - name: "source2raw1"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_ingst_s3_app01_detail/activities/source2raw1/source2raw1.json"
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 600000
      timeoutSeconds: 10800
  - name: "source2raw"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_ingst_s3_app01_detail/activities/source2raw/source2raw.json"
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: false
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 600000
      timeoutSeconds: 10800
  parameters:
  - name: "TableName"
    default: ""
  - name: "PartitionID"
    default: "2020-03-01"
  - name: "DatabaseName"
    default: "rawdata_tireo2o"
  - name: "LogEnabled"
    default: "1"
  - name: "MainPipelineTriggerType"
    default: ""
  - name: "env_storage"
    default: ""
  - name: "source_location"
    default: "tireo2o"
  - name: "source_filename"
    default: "app01_Online_Sales_[thedate].csv"
  - name: "source_type"
    default: "ablb"
  - name: "pl_name"
    default: ""
  variables:
  - name: "JobNameVar"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
