apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "d91f6c729bcc24cb7eb7a43cca216782"
spec:
  displayName: "pl_dbrs_fix_ingst_app01_hana_main"
  runAs: "Account/2100052957"
  trigger:
    type: "SCHEDULED"
    pauseStatus: "UNPAUSED"
    frequency: "daily"
    cronExpression: "0 1 8 * * ?"
    priority: "d5"
  activities:
  - name: "GetJobList"
    type: "look_up"
    dataSource: "pl_dbrs_fix_ingst_spm_hana_main_support_live_sanitized__ls_asql_infra_03"
    table: "<<REDACTED>>"
    dependsOn:
      activities:
      - name: "SetEndDate"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "GetPartitionID"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "partition_id"
    value:
      rawValue: "@if(equals(pipeline().parameters.PartitionID,'0'),formatDateTime(addhours(utcnow(),8),\
        \ 'yyyy-MM-dd'),pipeline().parameters.PartitionID)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "IterateEachJob"
    type: "for_each"
    items: "@activity('GetJobList').output.value"
    concurrency: 3
    activities:
    - name: "pl_dbrs_fix_ingst_app01_hana_detail"
      type: "execute_pipeline"
      pipelineName: "pl_dbrs_fix_ingst_app01_hana_detail"
      pipelineId: "c850a716927311a8b9c112905946aa71"
      projectId: "10926"
      bizDate: "${DATE}"
      pipelineParameterValues:
        LogEnabled: ""
        partition_id: ""
        DatabaseName: ""
        TableName: ""
        MainPipelineTriggerType: ""
        is_header: ""
        storage_account: ""
        DataSourceSQL_select: ""
        DataSourceSQL_from: ""
        DataSourceSQL_where: ""
        StartDate: ""
        EndDate: ""
        src_level_name: ""
      waitingSuccess: true
    dependsOn:
      activities:
      - name: "GetJobList"
        dependencyConditions:
        - "succeeded"
  - name: "Env"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "Env"
    value:
      rawValue: "@pipeline().globalParameters.Environment"
    outputVariables: []
  - name: "If_Condition1"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "{{pipeline.vars.Env}}"
      op: "EQUAL_TO"
      right: "INT"
    dependsOn:
      activities:
      - name: "Env"
        dependencyConditions:
        - "succeeded"
  - name: "storage_account_INT"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "storage_account"
    value:
      rawValue: "<<REDACTED>>"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "storage_account_prod"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "storage_account"
    value:
      rawValue: "<<REDACTED>>"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "SetStartDate_v2"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "StartDate_v2"
    value:
      rawValue: "@if(equals(pipeline().parameters.StartDate_v2,null),formatDateTime(adddays(addhours(utcnow(),8),-2),'yyyy-MM-dd'),pipeline().parameters.StartDate_v2)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "GetPartitionID"
        dependencyConditions:
        - "succeeded"
  - name: "SetStartDate"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "StartDate"
    value:
      rawValue: "@if(empty(pipeline().parameters.pStartDate), formatDateTime(addToTime(utcnow(),\
        \ -5, 'Month'), 'yyyy-MM-dd'), pipeline().parameters.pStartDate)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "SetStartDate_v2"
        dependencyConditions:
        - "succeeded"
  - name: "SetEndDate"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "EndDate"
    value:
      rawValue: "@if(empty(pipeline().parameters.pEndDate), formatDateTime(addhours(utcnow(),\
        \ +8), 'yyyy-MM-dd'), pipeline().parameters.pEndDate)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "SetStartDate"
        dependencyConditions:
        - "succeeded"
  parameters:
  - name: "LogEnabled"
    default: "1"
  - name: "TableName"
    default: "ALL"
  - name: "PartitionID"
    default: "0"
  - name: "is_header"
    default: "False"
  - name: "pStartDate"
    default: ""
  - name: "pEndDate"
    default: ""
  - name: "StartDate_v2"
    default: ""
  variables:
  - name: "partition_id"
    default: ""
  - name: "JobNameVar"
    default: ""
  - name: "Env"
    default: ""
  - name: "storage_account"
    default: ""
  - name: "StartDate"
    default: ""
  - name: "EndDate"
    default: ""
  - name: "StartDate_v2"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
