apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "a0b75834b04a289390c32446cb122ab2"
spec:
  displayName: "pl_dbrs_job_ingst_app01_psql_source_08_union_detail"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "StartLogRecord"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_ingst_app01_psql_source_08_union_detail/activities/StartLogRecord/StartLogRecord.json"
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "Copy2RawData"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_ingst_app01_psql_source_08_union_detail/activities/Copy2RawData/Copy2RawData.json"
    dependsOn:
      activities:
      - name: "Set_src_sql"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 2
      minRetryIntervalMillis: 600000
      timeoutSeconds: 82800
  - name: "If_Condition1"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "@Or(Equals(pipeline().TriggerType,'Manual'),Equals(pipeline().parameters.MainPipelineTriggerType,\
        \ 'Manual'))"
      op: "EQUAL_TO"
      right: "true"
  - name: "Manual"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@concat('$M$_', pipeline().parameters.TableName)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "Auto"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@pipeline().parameters.TableName"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "Set_SrcDatabaseName"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "SrcDatabaseName"
    value:
      rawValue: "@split(replace(pipeline().parameters.DataSourceSQL_FROM, 'from ',\
        \ ''), '.')[0]"
    outputVariables: []
    dependsOn:
      activities:
      - name: "StartLogRecord"
        dependencyConditions:
        - "succeeded"
  - name: "Set_SrcTableName"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "SrcTableName"
    value:
      rawValue: "@replace(pipeline().parameters.DataSourceSQL_FROM, 'from ', '')"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Set_SrcDatabaseName"
        dependencyConditions:
        - "succeeded"
  - name: "Get_src_sql"
    type: "look_up"
    dataSource: "ls_psql_source_08_new"
    table: "ds_uc_src_psql_app01_source_08_new"
    dependsOn:
      activities:
      - name: "Set_SrcTableName"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 5
      minRetryIntervalMillis: 30000
      timeoutSeconds: 3600
  - name: "Set_src_sql"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "src_sql"
    value:
      rawValue: "@activity('Get src_sql').output.firstRow.src_sql"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Get_src_sql"
        dependencyConditions:
        - "succeeded"
  parameters:
  - name: "pStartDate"
    default: ""
  - name: "pEndDate"
    default: ""
  - name: "logEnabled"
    default: "1"
  - name: "PartitionID"
    default: ""
  - name: "pl_name"
    default: ""
  - name: "MainPipelineTriggerType"
    default: ""
  - name: "DataSourceSQL_FROM"
    default: ""
  - name: "DatabaseName"
    default: ""
  - name: "DataSourceSQL"
    default: ""
  - name: "TableName"
    default: ""
  variables:
  - name: "JobNameVar"
    default: ""
  - name: "SrcDatabaseName"
    default: ""
  - name: "SrcTableName"
    default: ""
  - name: "source_sql"
    default: ""
  - name: "src_sql"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
