apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "db0abe7ce80335ca5f165e9c2590e887"
spec:
  displayName: "pl_dbrs_fix_ingst_app01_db2_detail"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "Set_PartitionID"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "PartitionID"
    value:
      rawValue: "@pipeline().parameters.PartitionID"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Check_TriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "Set_StagingDir"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "StagingDir"
    value:
      rawValue: "@replace(replace(pipeline().parameters.StagingDir, '{rw_db}', pipeline().parameters.RwDB),'{partition_date}',\
        \ variables('PartitionID'))"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Set_PartitionID"
        dependencyConditions:
        - "succeeded"
  - name: "StartLogRecord"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_db2_detail/activities/StartLogRecord/StartLogRecord.json"
    dependsOn:
      activities:
      - name: "Set_StagingDir"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "copy2blob"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_db2_detail/activities/copy2blob/copy2blob.json"
    dependsOn:
      activities:
      - name: "StartLogRecord"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "blob2rawdata2datalake"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_db2_detail/activities/blob2rawdata2datalake/blob2rawdata2datalake.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "copy2blob"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 2
      minRetryIntervalMillis: 240000
      timeoutSeconds: 43200
  - name: "log_landingzone"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_db2_detail/activities/log_landingzone/log_landingzone.json"
    dependsOn:
      activities:
      - name: "copy2blob"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "landingzone_failed"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_ingst_app01_db2_detail/activities/landingzone_failed/landingzone_failed.json"
    dependsOn:
      activities:
      - name: "copy2blob"
        dependencyConditions:
        - "failed"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  - name: "Check_TriggerType"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "@or(equals(pipeline().TriggerType,'Manual'),equals(pipeline().parameters.MainPipelineTriggerType,'Manual'))"
      op: "EQUAL_TO"
      right: "true"
  - name: "Set_JobName_Manual"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@concat('$M$_', pipeline().parameters.TableName)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Check_TriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "Set_JobName_Auto"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@pipeline().parameters.TableName"
    outputVariables: []
    dependsOn:
      activities:
      - name: "Check_TriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: false
  parameters:
  - name: "LogEnabled"
    default: "1"
  - name: "TableName"
    default: "ALL"
  - name: "PartitionID"
    default: ""
  - name: "is_header"
    default: "True"
  - name: "StagingContainer"
    default: ""
  - name: "StagingDir"
    default: ""
  - name: "StagingFile"
    default: ""
  - name: "RwDB"
    default: ""
  - name: "SourceTable"
    default: ""
  - name: "SelectSql"
    default: ""
  - name: "StorageAccount"
    default: ""
  - name: "MainPipelineTriggerType"
    default: ""
  - name: "src_level_name"
    default: ""
  variables:
  - name: "PartitionID"
    default: ""
  - name: "StagingDir"
    default: ""
  - name: "StartDate"
    default: ""
  - name: "EndDate"
    default: ""
  - name: "JobNameVar"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
