apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "acba4beb424bc922b242b767b1dad0aa"
spec:
  displayName: "pl_dbrs_job_ingst_tire_main2_support_live_sanitized__pl_dbrs_fix_ccdd_deletion"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "GetEnv"
    type: "look_up"
    dataSource: "pl_dbrs_job_ingst_tire_main2_support_live_sanitized__ls_asql_infra_04"
    table: "<<REDACTED>>"
    retryPolicy:
      maxRetries: 1
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "SetEnv"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "env"
    value:
      rawValue: "@json(activity('GetEnv').output.firstrow.env_storage).PROD_OR_INT"
    outputVariables: []
    dependsOn:
      activities:
      - name: "GetEnv"
        dependencyConditions:
        - "succeeded"
  - name: "set_datetime_from"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "datetime_from"
    value:
      rawValue: "@if(equals(pipeline().parameters.start_time_api,'NA'),formatDateTime(addDays(addHours(utcNow(),8),-1),'yyyy-MM-dd'),pipeline().parameters.start_time_api)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "SetEnv"
        dependencyConditions:
        - "succeeded"
  - name: "set_datetime_to"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "datetime_to"
    value:
      rawValue: "@if(equals(pipeline().parameters.end_time_api,'NA'),formatDateTime(addHours(utcNow(),8),'yyyy-MM-dd'),pipeline().parameters.end_time_api)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "set_datetime_from"
        dependencyConditions:
        - "succeeded"
  - name: "deletion"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_ingst_tire_main2_support_live_sanitized__pl_dbrs_fix_ccdd_deletion/activities/deletion/deletion.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "set_datetime_to"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 43200
  parameters:
  - name: "app_name"
    default: "oab"
  - name: "start_time_api"
    default: "NA"
  - name: "end_time_api"
    default: "NA"
  - name: "del_table_name"
    default: "NA"
  variables:
  - name: "datetime_from"
    default: ""
  - name: "datetime_to"
    default: ""
  - name: "conf"
    default: "{\"oab\":[\"rw_cust_otrplus_datalake_appointment\",\"rw_cust_otrplus_datalake_edrive_information\"\
      ,\"rw_cust_otrplus_datalake_my_information\"],\"oab_dw\":[\"dw_cust_otrplus_datalake_appointment\"\
      ,\"dw_cust_otrplus_datalake_edrive_information\",\"dw_cust_otrplus_datalake_my_information\"\
      ],\"ecom\":[\"rw_vhcl_ecommerce_dcp_order\",\"rw_vhcl_ecommerce_dcp_order_withvin\"\
      ,\"rw_cust_ecommerce_dcp_customer\",\"rw_cust_ecommerce_dcp_mmc_order\"],\"\
      occas\":[\"rw_part_tireo2o_order\",\"rw_cust_tireo2o_dealer_member_info\",\"\
      rw_cust_tireo2o_customer_loyalty_plan\",\"rw_srvc_tireo2o_order_order_status_transitions\"\
      ,\"rw_cust_tireo2o_order_order_base\",\"rw_cust_tireo2o_coupon_vertification_info\"\
      ,\"rw_cust_tireo2o_customer_right_coupon\"],\"cdm\":[\"rw_cust_cdm_digital_accnt\"\
      ,\"rw_rltnshp_cdm_digital_vhcl_relationship\"]}"
  - name: "d_tables"
    default: ""
  - name: "env"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
