apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "031afc221a9a7138bb6a1ada32dbd512"
spec:
  displayName: "pl_dbrs_fix_ingst_app01_file_main"
  runAs: "Account/2100052957"
  trigger:
    type: "SCHEDULED"
    pauseStatus: "UNPAUSED"
    frequency: "daily"
    cronExpression: "0 0 16 * * ?"
    priority: "d5"
  activities:
  - name: "GetJobList"
    type: "look_up"
    dataSource: "pl_dbrs_fix_ingst_rtm_file_main_support_live_sanitized__ls_asql_infra_05"
    table: "<<REDACTED>>"
    dependsOn:
      activities:
      - name: "Set_Partition_ID"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "IterateEachJob"
    type: "for_each"
    items: "@activity('GetJobList').output.value"
    concurrency: 5
    activities:
    - name: "If_Alarm_Table"
      type: "if_condition"
      description: "Conditional execution"
      condition:
        type: "BINARY_OP"
        left: "{{item.TableName}}"
        op: "CONTAINS"
        right: "rw_app01_alarm"
    - name: "pl_dbrs_fix_ingst_app01_file_detail2"
      type: "execute_pipeline"
      pipelineName: "pl_dbrs_fix_ingst_app01_file_detail2"
      pipelineId: "1e4a1c408eb45a4d4ecd9642cab0bb21"
      projectId: "10926"
      bizDate: "${DATE}"
      pipelineParameterValues:
        LogEnabled: ""
        partition_id: ""
        DatabaseName: ""
        TableName: ""
        MainPipelineTriggerType: ""
        is_header: ""
        storage_account: ""
        DataSourcePath: ""
      waitingSuccess: true
      dependsOn:
        activities:
        - name: "If_Alarm_Table"
          dependencyConditions:
          - "succeeded"
          outcome: true
    - name: "pl_dbrs_fix_ingst_app01_file_detail1"
      type: "execute_pipeline"
      pipelineName: "pl_dbrs_fix_ingst_app01_file_detail1"
      pipelineId: "eabbfff0b765ef6ea0640b22f51fd3a8"
      projectId: "10926"
      bizDate: "${DATE}"
      pipelineParameterValues:
        LogEnabled: ""
        partition_id: ""
        DatabaseName: ""
        TableName: ""
        MainPipelineTriggerType: ""
        is_header: ""
        storage_account: ""
        DataSourcePath: ""
        src_level_name: ""
      waitingSuccess: true
      dependsOn:
        activities:
        - name: "If_Alarm_Table"
          dependencyConditions:
          - "succeeded"
          outcome: false
    dependsOn:
      activities:
      - name: "GetJobList"
        dependencyConditions:
        - "succeeded"
  - name: "Env"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "Env"
    value:
      rawValue: "@pipeline().globalParameters.Environment"
    outputVariables: []
  - name: "If_Condition1"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "{{pipeline.vars.Env}}"
      op: "EQUAL_TO"
      right: "INT"
    dependsOn:
      activities:
      - name: "Env"
        dependencyConditions:
        - "succeeded"
  - name: "storage_account_INT"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "storage_account"
    value:
      rawValue: "<<REDACTED>>"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "storage_account_prod"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "storage_account"
    value:
      rawValue: "<<REDACTED>>"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "Set_Partition_ID"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "partition_id"
    value:
      rawValue: "@if(equals(pipeline().parameters.PartitionID,'0'),formatDateTime(adddays(addhours(utcnow(),\
        \ 8),-1), 'yyyy-MM-dd'),pipeline().parameters.PartitionID)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "If_Condition1"
        dependencyConditions:
        - "succeeded"
        outcome: true
  parameters:
  - name: "LogEnabled"
    default: "1"
  - name: "TableName"
    default: "source_table_1,source_table_2,source_table_3,source_table_4,source_table_5"
  - name: "PartitionID"
    default: "0"
  - name: "is_header"
    default: "False"
  variables:
  - name: "partition_id"
    default: ""
  - name: "JobNameVar"
    default: ""
  - name: "Env"
    default: ""
  - name: "storage_account"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
