apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "77acca7507f62a8970858ad035230c38"
spec:
  displayName: "pl_dbrs_job_app01_psql_app01_promotion_detail"
  description: "<<REDACTED>>"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "StartLogRecord"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_app01_psql_app01_promotion_detail/activities/StartLogRecord/StartLogRecord.json"
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "CheckTriggerType"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "@or(equals(pipeline().TriggerType,'Manual'),equals(pipeline().parameters.IsParentPipelineManualTrigger,'Manual'))"
      op: "EQUAL_TO"
      right: "true"
  - name: "SetJobNameManual"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@concat('$M$_', pipeline().parameters.TableName)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "SetJobNameAuto"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@pipeline().parameters.TableName"
    outputVariables: []
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "ecommerce2rw"
    type: "dts_batch"
    description: "A new Copy Data job"
    source: "WORKSPACE"
    engineType: "dts_batch"
    path: "/Workspace/libopeng_folder/pl_dbrs_job_app01_psql_app01_promotion_detail/activities/ecommerce2rw/ecommerce2rw.json"
    dependsOn:
      activities:
      - name: "RowDataCount"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 600000
      timeoutSeconds: 10800
  - name: "RowDataCount"
    type: "look_up"
    dataSource: "ls_psql_app01_app01_promotion"
    table: "ds_src_psql_app01_app01_promotion"
    dependsOn:
      activities:
      - name: "StartLogRecord"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 2
      minRetryIntervalMillis: 120000
      timeoutSeconds: 43200
  parameters:
  - name: "DatabaseName"
    default: "rawdata_app01"
  - name: "TableName"
    default: "rw_srvc_app01_mmc_mystar_homepage_banner"
  - name: "PartitionID"
    default: "2023-03-29"
  - name: "LogEnabled"
    default: "1"
  - name: "IsParentPipelineManualTrigger"
    default: "Manual"
  - name: "select_sql"
    default: "SELECT id,REPLACE(REPLACE(title,CHR(10),''),CHR(13),'') as title,REPLACE(REPLACE(sub_title,CHR(10),''),CHR(13),'')\
      \ as sub_title,sort,personalized,segment_id,REPLACE(REPLACE(segment_name,CHR(10),''),CHR(13),'')\
      \ as segment_name,created_time+'8H' as created_time,modified_time+'8H' as modified_time,REPLACE(REPLACE(product_codes,CHR(10),''),CHR(13),'')\
      \ as product_codes,start_time+'8H' as start_time,end_time+'8H' as end_time,REPLACE(REPLACE(approval_status,CHR(10),''),CHR(13),'')\
      \ as approval_status,active,REPLACE(REPLACE(campaign_code,CHR(10),''),CHR(13),'')\
      \ as campaign_code,LOCALTIMESTAMP+'8H' as last_mdf_dt from mmc_mystar_homepage_banner\
      \ T where   modified_time  >= '1901-01-01' and modified_time  < '2025-08-07T16:00:00.000Z'"
  - name: "SQLFrom"
    default: "from mmc_mystar_homepage_banner"
  - name: "SQLWhere"
    default: "modified_time  >= '1901-01-01' and modified_time  < '2025-08-07T16:00:00.000Z'"
  - name: "pl_name"
    default: ""
  variables:
  - name: "JobNameVar"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
