apiVersion: "newide.studio.dataleap.volc/v1"
kind: "Pipeline"
metadata:
  name: "aa7c4354bf05f6b26e87e1b89bd5221a"
spec:
  displayName: "pl_dbrs_fix_app01_ddq_detail"
  runAs: "Account/2100052957"
  trigger:
    type: "MANUAL"
  activities:
  - name: "Ingest"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_app01_ddq_detail/activities/Ingest/Ingest.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "tar_gz"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 2
      minRetryIntervalMillis: 240000
      timeoutSeconds: 10800
  - name: "StartLogRecord"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_app01_ddq_detail/activities/StartLogRecord/StartLogRecord.json"
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "CopyData_fail"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_app01_ddq_detail/activities/CopyData_fail/CopyData_fail.json"
    dependsOn:
      activities:
      - name: "tar_gz"
        dependencyConditions:
        - "failed"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "Ingest_fail"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_app01_ddq_detail/activities/Ingest_fail/Ingest_fail.json"
    dependsOn:
      activities:
      - name: "Ingest"
        dependencyConditions:
        - "failed"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "LogCount"
    type: "custom"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_app01_ddq_detail/activities/LogCount/LogCount.json"
    dependsOn:
      activities:
      - name: "Ingest"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 0
      minRetryIntervalMillis: 30000
      timeoutSeconds: 604800
  - name: "CheckTriggerType"
    type: "if_condition"
    description: "Conditional execution"
    condition:
      type: "BINARY_OP"
      left: "@Or(Equals(pipeline().TriggerType,'Manual'),Equals(pipeline().parameters.MainPipelineTriggerType,\
        \ 'Manual'))"
      op: "EQUAL_TO"
      right: "true"
  - name: "SetJobNameManual"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@concat('$M$_', pipeline().parameters.TableName)"
    outputVariables: []
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: true
  - name: "SetJobNameAuto"
    type: "set_variable"
    description: "Set a pipeline variable"
    variableType: "PIPELINE_INNER"
    variableName: "JobNameVar"
    value:
      rawValue: "@pipeline().parameters.TableName"
    outputVariables: []
    dependsOn:
      activities:
      - name: "CheckTriggerType"
        dependencyConditions:
        - "succeeded"
        outcome: false
  - name: "tar_gz"
    type: "notebook"
    description: "A new Notebook job"
    source: "WORKSPACE"
    path: "/Workspace/libopeng_folder/pl_dbrs_fix_app01_ddq_detail/activities/tar_gz/tar_gz.ipynb"
    kernelType: "emr_serverless_spark_python"
    engineQueue: "公共队列-Default"
    computingResourceGroupName: "public_compute"
    computingResourceGroupId: 1012
    sparkConf: []
    executeParam:
      image:
        imageUrl: ""
    parameters: []
    resources: []
    dependsOn:
      activities:
      - name: "StartLogRecord"
        dependencyConditions:
        - "succeeded"
    retryPolicy:
      maxRetries: 3
      minRetryIntervalMillis: 300000
      timeoutSeconds: 10800
  parameters:
  - name: "MainPipelineTriggerType"
    default: ""
  - name: "LogEnabled"
    default: ""
  - name: "DatabaseName"
    default: ""
  - name: "PartitionID"
    default: ""
  - name: "dir_prefix"
    default: ""
  - name: "FileName"
    default: ""
  - name: "TableName"
    default: ""
  - name: "data_location"
    default: ""
  - name: "select_column"
    default: ""
  - name: "env"
    default: ""
  variables:
  - name: "JobNameVar"
    default: ""
  schedulingResourceGroupName: "public_schedule"
  schedulingResourceGroupId: 1009
  dependsOn:
    pipelines: []
    self:
      enabled: false
